# Generated by Django 5.2.5 on 2026-02-01 13:22

import ckeditor_uploader.fields
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BlogCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Blog Category",
                "verbose_name_plural": "Blog Categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BlogTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("slug", models.SlugField(blank=True, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Certification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("issuing_organization", models.CharField(max_length=200)),
                (
                    "organization_logo",
                    models.ImageField(
                        blank=True, null=True, upload_to="certifications/"
                    ),
                ),
                ("issue_date", models.DateField()),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("credential_id", models.CharField(blank=True, max_length=200)),
                ("credential_url", models.URLField(blank=True)),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-issue_date"],
            },
        ),
        migrations.CreateModel(
            name="ContactMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("budget", models.CharField(blank=True, max_length=100)),
                ("project_type", models.CharField(blank=True, max_length=100)),
                ("is_read", models.BooleanField(default=False)),
                ("is_replied", models.BooleanField(default=False)),
                ("admin_notes", models.TextField(blank=True)),
            ],
            options={
                "verbose_name": "Contact Message",
                "verbose_name_plural": "Contact Messages",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Education",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("degree", models.CharField(max_length=200)),
                ("field_of_study", models.CharField(blank=True, max_length=200)),
                ("institution", models.CharField(max_length=200)),
                (
                    "institution_logo",
                    models.ImageField(blank=True, null=True, upload_to="education/"),
                ),
                ("location", models.CharField(blank=True, max_length=200)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        help_text="e.g., 3.8 GPA, First Class",
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Education",
                "verbose_name_plural": "Education",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="Experience",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("job_title", models.CharField(max_length=200)),
                ("company", models.CharField(max_length=200)),
                ("company_url", models.URLField(blank=True)),
                (
                    "company_logo",
                    models.ImageField(blank=True, null=True, upload_to="experience/"),
                ),
                ("location", models.CharField(blank=True, max_length=200)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("is_current", models.BooleanField(default=False)),
                ("description", ckeditor_uploader.fields.RichTextUploadingField()),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Work Experience",
                "verbose_name_plural": "Work Experiences",
                "ordering": ["-start_date"],
            },
        ),
        migrations.CreateModel(
            name="NewsletterSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Newsletter Subscriber",
                "verbose_name_plural": "Newsletter Subscribers",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProfileSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "title",
                    models.CharField(
                        help_text="e.g., Full Stack Developer", max_length=200
                    ),
                ),
                (
                    "subtitle",
                    models.CharField(
                        blank=True, help_text="Tagline or short intro", max_length=300
                    ),
                ),
                (
                    "typing_texts",
                    models.CharField(
                        blank=True,
                        default="Developer,Designer,Creator",
                        help_text="Comma-separated texts for typing animation",
                        max_length=500,
                    ),
                ),
                (
                    "profile_image",
                    models.ImageField(blank=True, null=True, upload_to="profile/"),
                ),
                (
                    "cover_image",
                    models.ImageField(blank=True, null=True, upload_to="profile/"),
                ),
                (
                    "resume",
                    models.FileField(blank=True, null=True, upload_to="resume/"),
                ),
                (
                    "bio_short",
                    models.TextField(
                        help_text="Short bio for homepage (2-3 sentences)"
                    ),
                ),
                (
                    "bio_full",
                    ckeditor_uploader.fields.RichTextUploadingField(
                        blank=True, help_text="Full bio for about page"
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                (
                    "whatsapp",
                    models.CharField(
                        blank=True,
                        help_text="With country code, no + sign",
                        max_length=20,
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=200)),
                ("github", models.URLField(blank=True)),
                ("linkedin", models.URLField(blank=True)),
                ("twitter", models.URLField(blank=True)),
                ("instagram", models.URLField(blank=True)),
                ("youtube", models.URLField(blank=True)),
                ("dribbble", models.URLField(blank=True)),
                ("behance", models.URLField(blank=True)),
                ("medium", models.URLField(blank=True)),
                ("dev_to", models.URLField(blank=True, verbose_name="Dev.to")),
                ("facebook", models.URLField(blank=True)),
                ("tiktok", models.URLField(blank=True)),
                ("website", models.URLField(blank=True)),
                ("years_experience", models.PositiveIntegerField(default=0)),
                ("projects_completed", models.PositiveIntegerField(default=0)),
                ("happy_clients", models.PositiveIntegerField(default=0)),
                ("awards_won", models.PositiveIntegerField(default=0)),
                ("is_available_for_hire", models.BooleanField(default=True)),
                (
                    "availability_status",
                    models.CharField(
                        blank=True,
                        default="Available for Work",
                        help_text="e.g., Available for freelance",
                        max_length=100,
                    ),
                ),
                (
                    "theme_mode",
                    models.CharField(
                        choices=[
                            ("gradient", "Gradient Colors"),
                            ("solid", "Solid Colors"),
                        ],
                        default="gradient",
                        help_text="Choose between gradient or solid color theme",
                        max_length=20,
                    ),
                ),
                (
                    "gradient_preset",
                    models.CharField(
                        choices=[
                            ("purple-blue", "Purple to Blue (#667eea → #764ba2)"),
                            ("cyan-blue", "Cyan to Blue (#4facfe → #00f2fe)"),
                            ("pink-orange", "Pink to Orange (#f093fb → #f5576c)"),
                            ("green-teal", "Green to Teal (#11998e → #38ef7d)"),
                            ("orange-red", "Orange to Red (#ff512f → #f09819)"),
                            ("blue-purple", "Blue to Purple (#667eea → #764ba2)"),
                            ("pink-purple", "Pink to Purple (#f953c6 → #b91d73)"),
                            ("gold-orange", "Gold to Orange (#f7971e → #ffd200)"),
                            ("teal-green", "Teal to Green (#00b09b → #96c93d)"),
                            ("red-pink", "Red to Pink (#ed213a → #93291e)"),
                            ("ocean", "Ocean Blue (#2193b0 → #6dd5ed)"),
                            ("sunset", "Sunset (#ff7e5f → #feb47b)"),
                            ("custom", "Custom Gradient"),
                        ],
                        default="purple-blue",
                        help_text="Select a gradient preset",
                        max_length=50,
                    ),
                ),
                (
                    "custom_gradient_start",
                    models.CharField(
                        blank=True,
                        default="#667eea",
                        help_text="Start color (hex) for custom gradient",
                        max_length=7,
                    ),
                ),
                (
                    "custom_gradient_end",
                    models.CharField(
                        blank=True,
                        default="#764ba2",
                        help_text="End color (hex) for custom gradient",
                        max_length=7,
                    ),
                ),
                (
                    "solid_color_preset",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("#667eea", "Purple"),
                            ("#4facfe", "Cyan"),
                            ("#f093fb", "Pink"),
                            ("#11998e", "Teal"),
                            ("#ff512f", "Orange"),
                            ("#f953c6", "Magenta"),
                            ("#f7971e", "Gold"),
                            ("#ed213a", "Red"),
                            ("#2193b0", "Ocean"),
                            ("#00b09b", "Green"),
                            ("custom", "Custom Color"),
                        ],
                        default="#667eea",
                        max_length=20,
                    ),
                ),
                (
                    "custom_solid_color",
                    models.CharField(
                        blank=True,
                        default="#667eea",
                        help_text="Custom solid color (hex)",
                        max_length=7,
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        default="#00f2fe",
                        help_text="Accent color for highlights (hex)",
                        max_length=7,
                    ),
                ),
                (
                    "bg_dark",
                    models.CharField(
                        default="#0f172a",
                        help_text="Main background color",
                        max_length=7,
                    ),
                ),
                (
                    "bg_card",
                    models.CharField(
                        default="#1e293b",
                        help_text="Card/glass background color",
                        max_length=7,
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=60)),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                ("meta_keywords", models.CharField(blank=True, max_length=255)),
                ("google_analytics_id", models.CharField(blank=True, max_length=50)),
                ("footer_text", models.CharField(blank=True, max_length=200)),
                (
                    "show_powered_by",
                    models.BooleanField(
                        default=True,
                        help_text="⚠️ Please keep this enabled to support the developers",
                    ),
                ),
            ],
            options={
                "verbose_name": "Profile Setting",
                "verbose_name_plural": "Profile Settings",
            },
        ),
        migrations.CreateModel(
            name="ProjectCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Project Category",
                "verbose_name_plural": "Project Categories",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("icon", models.CharField(blank=True, max_length=50)),
                ("short_description", models.TextField()),
                (
                    "description",
                    ckeditor_uploader.fields.RichTextUploadingField(blank=True),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="services/"),
                ),
                (
                    "price_starting",
                    models.CharField(blank=True, help_text="e.g., $500", max_length=50),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SkillCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name": "Skill Category",
                "verbose_name_plural": "Skill Categories",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="SocialLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=100)),
                ("url", models.URLField()),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Font Awesome class (e.g., fa-link)",
                        max_length=50,
                    ),
                ),
                ("description", models.CharField(blank=True, max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="Show prominently on homepage"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Link / Social",
                "verbose_name_plural": "Links / Socials",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("featured_image", models.ImageField(upload_to="blog/")),
                ("excerpt", models.TextField(help_text="Short summary for cards")),
                ("content", ckeditor_uploader.fields.RichTextUploadingField()),
                ("meta_title", models.CharField(blank=True, max_length=60)),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                (
                    "published_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_published", models.BooleanField(default=True)),
                ("views", models.PositiveIntegerField(default=0)),
                (
                    "reading_time",
                    models.PositiveIntegerField(default=5, help_text="Minutes to read"),
                ),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="core.blogcategory",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="posts", to="core.blogtag"
                    ),
                ),
            ],
            options={
                "verbose_name": "Blog Post",
                "verbose_name_plural": "Blog Posts",
                "ordering": ["-published_date"],
            },
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("thumbnail", models.ImageField(upload_to="projects/thumbnails/")),
                (
                    "featured_image",
                    models.ImageField(blank=True, null=True, upload_to="projects/"),
                ),
                ("short_description", models.TextField()),
                ("description", ckeditor_uploader.fields.RichTextUploadingField()),
                ("client", models.CharField(blank=True, max_length=200)),
                ("project_date", models.DateField(blank=True, null=True)),
                (
                    "project_url",
                    models.URLField(blank=True, help_text="Live project URL"),
                ),
                ("github_url", models.URLField(blank=True)),
                (
                    "technologies",
                    models.CharField(
                        blank=True,
                        help_text="Comma-separated technologies",
                        max_length=500,
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=60)),
                ("meta_description", models.CharField(blank=True, max_length=160)),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="projects",
                        to="core.projectcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-project_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProjectImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="projects/gallery/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "project",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Skill",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=100)),
                (
                    "icon",
                    models.CharField(
                        blank=True,
                        help_text="Font Awesome class or icon name",
                        max_length=50,
                    ),
                ),
                (
                    "proficiency",
                    models.PositiveIntegerField(
                        default=80, help_text="0-100 percentage"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skills",
                        to="core.skillcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Testimonial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("client_name", models.CharField(max_length=200)),
                (
                    "client_title",
                    models.CharField(
                        blank=True, help_text="e.g., CEO at Company", max_length=200
                    ),
                ),
                (
                    "client_photo",
                    models.ImageField(blank=True, null=True, upload_to="testimonials/"),
                ),
                ("client_company", models.CharField(blank=True, max_length=200)),
                ("content", models.TextField()),
                (
                    "rating",
                    models.PositiveIntegerField(
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=5
                    ),
                ),
                ("is_featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "project",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.project",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
